import type { Product } from "./types"

export const mockProducts: Product[] = [
  // ============ ELECTRONICS ============
  {
    id: "prod-1",
    name: "iPhone 15 Pro",
    category: "electronics",
    brand: "Apple",
    description: "Premium smartphone with advanced camera system and A17 Pro chip",
    image: "https://images.unsplash.com/photo-1592286927505-1fed5fa27fcd?w=400&h=400&fit=crop",
    specifications: {
      display: "6.1 inch OLED",
      processor: "A17 Pro",
      ram: "8GB",
      storage: "256GB",
      camera: "48MP + 12MP",
      battery: "3200 mAh",
    },
    prices: [
      {
        retailer: "Amazon India",
        price: 79999,
        currency: "INR",
        url: "https://amazon.in",
        availability: "in_stock",
      },
      {
        retailer: "Flipkart",
        price: 79999,
        currency: "INR",
        url: "https://flipkart.com",
        availability: "in_stock",
      },
      {
        retailer: "Apple Store",
        price: 89999,
        currency: "INR",
        url: "https://apple.com",
        availability: "in_stock",
      },
      {
        retailer: "Croma",
        price: 84999,
        currency: "INR",
        url: "https://croma.com",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.8, count: 2543 },
    tags: ["flagship", "premium", "new"],
  },
  {
    id: "prod-2",
    name: "Samsung Galaxy S24",
    category: "electronics",
    brand: "Samsung",
    description: "Latest Android flagship with AI features and 50MP camera",
    image: "https://images.unsplash.com/photo-1610945414563-52f63cb88de0?w=400&h=400&fit=crop",
    specifications: {
      display: "6.2 inch AMOLED",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB",
      storage: "256GB",
      camera: "50MP + 12MP + 10MP",
      battery: "4000 mAh",
    },
    prices: [
      {
        retailer: "Amazon India",
        price: 74999,
        currency: "INR",
        url: "https://amazon.in",
        availability: "in_stock",
      },
      {
        retailer: "Flipkart",
        price: 72999,
        currency: "INR",
        url: "https://flipkart.com",
        availability: "in_stock",
      },
      {
        retailer: "Samsung Store",
        price: 79999,
        currency: "INR",
        url: "https://samsung.com",
        availability: "limited",
      },
    ],
    ratings: { average: 4.7, count: 1892 },
    tags: ["flagship", "android", "new"],
  },
  {
    id: "prod-3",
    name: "OnePlus 12",
    category: "electronics",
    brand: "OnePlus",
    description: "Fast flagship killer phone with 5400 mAh battery",
    image: "https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400&h=400&fit=crop",
    specifications: {
      display: "6.7 inch AMOLED",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB",
      storage: "256GB",
      camera: "50MP + 8MP + 48MP",
      battery: "5400 mAh",
    },
    prices: [
      {
        retailer: "Amazon India",
        price: 59999,
        currency: "INR",
        url: "https://amazon.in",
        availability: "in_stock",
      },
      {
        retailer: "Flipkart",
        price: 58999,
        currency: "INR",
        url: "https://flipkart.com",
        availability: "in_stock",
      },
      {
        retailer: "OnePlus Store",
        price: 64999,
        currency: "INR",
        url: "https://oneplus.com",
        availability: "limited",
      },
    ],
    ratings: { average: 4.6, count: 1234 },
    tags: ["performance", "value", "fast-charging"],
  },
  {
    id: "prod-4",
    name: "Redmi Note 13 Pro",
    category: "electronics",
    brand: "Xiaomi",
    description: "Affordable mid-range phone with 108MP camera",
    image: "https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400&h=400&fit=crop",
    specifications: {
      display: "6.67 inch AMOLED",
      processor: "Snapdragon 7 Gen 1",
      ram: "12GB",
      storage: "256GB",
      camera: "108MP + 8MP + 2MP",
      battery: "5000 mAh",
    },
    prices: [
      {
        retailer: "Amazon India",
        price: 27999,
        currency: "INR",
        url: "https://amazon.in",
        availability: "in_stock",
      },
      {
        retailer: "Flipkart",
        price: 26999,
        currency: "INR",
        url: "https://flipkart.com",
        availability: "in_stock",
      },
      {
        retailer: "Xiaomi Store",
        price: 29999,
        currency: "INR",
        url: "https://xiaomi.com",
        availability: "limited",
      },
    ],
    ratings: { average: 4.5, count: 3456 },
    tags: ["budget", "value", "camera"],
  },
  {
    id: "prod-5",
    name: "MacBook Pro 16",
    category: "electronics",
    brand: "Apple",
    description: "Powerful laptop with M3 Max chip for professionals",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop",
    specifications: {
      display: "16 inch Liquid Retina XDR",
      processor: "Apple M3 Max",
      ram: "36GB",
      storage: "512GB SSD",
      gpu: "GPU 30-core",
      battery: "100Wh",
    },
    prices: [
      {
        retailer: "Apple Store",
        price: 249900,
        currency: "INR",
        url: "https://apple.com",
        availability: "in_stock",
      },
      {
        retailer: "Amazon India",
        price: 239999,
        currency: "INR",
        url: "https://amazon.in",
        availability: "in_stock",
      },
      {
        retailer: "Flipkart",
        price: 244999,
        currency: "INR",
        url: "https://flipkart.com",
        availability: "limited",
      },
    ],
    ratings: { average: 4.9, count: 876 },
    tags: ["laptop", "professional", "premium"],
  },
  {
    id: "prod-6",
    name: "Dell XPS 13",
    category: "electronics",
    brand: "Dell",
    description: "Ultraportable laptop with Intel Core i7 processor",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop",
    specifications: {
      display: "13.3 inch FHD",
      processor: "Intel Core i7",
      ram: "16GB",
      storage: "512GB SSD",
      gpu: "Iris Xe Graphics",
      battery: "55Wh",
    },
    prices: [
      {
        retailer: "Dell Store",
        price: 119999,
        currency: "INR",
        url: "https://dell.com",
        availability: "in_stock",
      },
      {
        retailer: "Amazon India",
        price: 114999,
        currency: "INR",
        url: "https://amazon.in",
        availability: "in_stock",
      },
      {
        retailer: "Flipkart",
        price: 117999,
        currency: "INR",
        url: "https://flipkart.com",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.6, count: 654 },
    tags: ["laptop", "portable", "professional"],
  },
  {
    id: "prod-7",
    name: "Sony WH-1000XM5",
    category: "electronics",
    brand: "Sony",
    description: "Premium noise-canceling headphones with 30-hour battery",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    specifications: {
      type: "Over-ear wireless",
      driver: "40mm",
      frequency: "4Hz - 40kHz",
      battery: "30 hours",
      features: "ANC, LDAC, Ambient Mode",
    },
    prices: [
      { retailer: "Amazon India", price: 29999, currency: "INR", url: "https://amazon.in", availability: "in_stock" },
      {
        retailer: "Sony Store",
        price: 32490,
        currency: "INR",
        url: "https://sony.com",
        availability: "in_stock",
      },
      {
        retailer: "Flipkart",
        price: 28999,
        currency: "INR",
        url: "https://flipkart.com",
        availability: "limited",
      },
    ],
    ratings: { average: 4.7, count: 2134 },
    tags: ["headphones", "premium", "audio"],
  },
  {
    id: "prod-8",
    name: "Boat Airdopes 131",
    category: "electronics",
    brand: "Boat",
    description: "Affordable true wireless earbuds with good battery life",
    image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop",
    specifications: {
      type: "True wireless earbuds",
      driver: "6mm",
      frequency: "20Hz - 20kHz",
      battery: "8 hours",
      features: "Touch controls, Fast charging",
    },
    prices: [
      { retailer: "Amazon India", price: 1299, currency: "INR", url: "https://amazon.in", availability: "in_stock" },
      { retailer: "Flipkart", price: 1099, currency: "INR", url: "https://flipkart.com", availability: "in_stock" },
      {
        retailer: "Boat Store",
        price: 1499,
        currency: "INR",
        url: "https://boatlifestyle.com",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.2, count: 5678 },
    tags: ["earbuds", "budget", "wireless"],
  },

  // ============ CLOTHING ============
  {
    id: "prod-9",
    name: "Nike Air Max 90",
    category: "clothing",
    brand: "Nike",
    description: "Classic lifestyle sneaker with air cushioning",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    specifications: {
      material: "Leather & Mesh",
      size_range: "6-14 (UK)",
      colors_available: "5",
      gender: "Unisex",
      warranty: "1 Year",
    },
    prices: [
      { retailer: "Nike.com", price: 8999, currency: "INR", url: "https://nike.com", availability: "in_stock" },
      { retailer: "Amazon India", price: 7499, currency: "INR", url: "https://amazon.in", availability: "in_stock" },
      { retailer: "Flipkart", price: 7799, currency: "INR", url: "https://flipkart.com", availability: "in_stock" },
      {
        retailer: "Myntra",
        price: 6999,
        currency: "INR",
        url: "https://myntra.com",
        availability: "limited",
      },
    ],
    ratings: { average: 4.5, count: 5678 },
    tags: ["sneakers", "lifestyle", "casual"],
  },
  {
    id: "prod-10",
    name: "Adidas Ultraboost 22",
    category: "clothing",
    brand: "Adidas",
    description: "Performance running shoe with Boost technology",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    specifications: {
      material: "Primeknit",
      size_range: "5-13 (UK)",
      colors_available: "5",
      gender: "Unisex",
      warranty: "1 Year",
    },
    prices: [
      {
        retailer: "Adidas.com",
        price: 13999,
        currency: "INR",
        url: "https://adidas.com",
        availability: "in_stock",
      },
      {
        retailer: "Amazon India",
        price: 11999,
        currency: "INR",
        url: "https://amazon.in",
        availability: "in_stock",
      },
      {
        retailer: "Myntra",
        price: 10999,
        currency: "INR",
        url: "https://myntra.com",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.7, count: 3456 },
    tags: ["running", "performance", "sports"],
  },
  {
    id: "prod-11",
    name: "Puma RS-X",
    category: "clothing",
    brand: "Puma",
    description: "Retro-inspired casual sneaker with modern comfort",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    specifications: {
      material: "Suede & Nylon",
      size_range: "6-12 (UK)",
      colors_available: "3",
      gender: "Unisex",
      warranty: "1 Year",
    },
    prices: [
      { retailer: "Puma.com", price: 5999, currency: "INR", url: "https://puma.com", availability: "in_stock" },
      {
        retailer: "Amazon India",
        price: 4999,
        currency: "INR",
        url: "https://amazon.in",
        availability: "in_stock",
      },
      { retailer: "Flipkart", price: 5299, currency: "INR", url: "https://flipkart.com", availability: "in_stock" },
    ],
    ratings: { average: 4.4, count: 2345 },
    tags: ["sneakers", "casual", "retro"],
  },
  {
    id: "prod-12",
    name: "Allen Solly Shirt",
    category: "clothing",
    brand: "Allen Solly",
    description: "Premium cotton formal shirt for men",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&h=400&fit=crop",
    specifications: {
      material: "100% Cotton",
      size_range: "XS-XXL",
      colors_available: "6",
      gender: "Men",
      care: "Machine wash",
    },
    prices: [
      {
        retailer: "Allen Solly",
        price: 3499,
        currency: "INR",
        url: "https://allensolly.com",
        availability: "in_stock",
      },
      {
        retailer: "Amazon India",
        price: 2799,
        currency: "INR",
        url: "https://amazon.in",
        availability: "in_stock",
      },
      {
        retailer: "Myntra",
        price: 2499,
        currency: "INR",
        url: "https://myntra.com",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.3, count: 1234 },
    tags: ["formal", "shirt", "men"],
  },
  {
    id: "prod-13",
    name: "Fabindia Kurta",
    category: "clothing",
    brand: "Fabindia",
    description: "Ethnic hand-woven cotton kurta",
    image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400&h=400&fit=crop",
    specifications: {
      material: "Hand-woven cotton",
      size_range: "XS-XL",
      colors_available: "4",
      gender: "Women",
      care: "Hand wash",
    },
    prices: [
      {
        retailer: "Fabindia.com",
        price: 2999,
        currency: "INR",
        url: "https://fabindia.com",
        availability: "in_stock",
      },
      {
        retailer: "Amazon India",
        price: 2499,
        currency: "INR",
        url: "https://amazon.in",
        availability: "limited",
      },
    ],
    ratings: { average: 4.6, count: 876 },
    tags: ["ethnic", "kurta", "women"],
  },

  // ============ FLIGHTS ============
  {
    id: "prod-14",
    name: "Delhi to Mumbai - IndiGo (6:00 PM)",
    category: "flights",
    brand: "IndiGo",
    description: "2h 10min non-stop flight departing 6:00 PM",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400&h=400&fit=crop",
    specifications: {
      departure: "6:00 PM",
      duration: "2h 10min",
      stops: "Non-stop",
      aircraft: "A320",
      date: "Dec 15, 2024",
    },
    prices: [
      {
        retailer: "IndiGo Official",
        price: 3499,
        currency: "INR",
        url: "https://goindigo.in",
        availability: "in_stock",
      },
      {
        retailer: "MakeMyTrip",
        price: 3899,
        currency: "INR",
        url: "https://makemytrip.com",
        availability: "in_stock",
      },
      {
        retailer: "Cleartrip",
        price: 3799,
        currency: "INR",
        url: "https://cleartrip.com",
        availability: "limited",
      },
      {
        retailer: "Skyscanner",
        price: 3599,
        currency: "INR",
        url: "https://skyscanner.in",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.3, count: 8934 },
    tags: ["domestic", "economy", "evening"],
  },
  {
    id: "prod-15",
    name: "Mumbai to Bangalore - Air India (8:30 AM)",
    category: "flights",
    brand: "Air India",
    description: "1h 45min non-stop flight with meals included",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400&h=400&fit=crop",
    specifications: {
      departure: "8:30 AM",
      duration: "1h 45min",
      stops: "Non-stop",
      aircraft: "Boeing 737",
      date: "Dec 15, 2024",
    },
    prices: [
      {
        retailer: "Air India Official",
        price: 4299,
        currency: "INR",
        url: "https://airindia.in",
        availability: "in_stock",
      },
      {
        retailer: "MakeMyTrip",
        price: 4799,
        currency: "INR",
        url: "https://makemytrip.com",
        availability: "in_stock",
      },
      {
        retailer: "Cleartrip",
        price: 4599,
        currency: "INR",
        url: "https://cleartrip.com",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.1, count: 5678 },
    tags: ["domestic", "economy", "morning"],
  },
  {
    id: "prod-16",
    name: "Bangalore to Delhi - SpiceJet (5:15 PM)",
    category: "flights",
    brand: "SpiceJet",
    description: "2h 30min non-stop flight with 1 stop option",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400&h=400&fit=crop",
    specifications: {
      departure: "5:15 PM",
      duration: "2h 30min",
      stops: "Non-stop",
      aircraft: "Boeing 737",
      date: "Dec 16, 2024",
    },
    prices: [
      {
        retailer: "SpiceJet Official",
        price: 2999,
        currency: "INR",
        url: "https://spicejet.com",
        availability: "in_stock",
      },
      {
        retailer: "Cleartrip",
        price: 3299,
        currency: "INR",
        url: "https://cleartrip.com",
        availability: "in_stock",
      },
      {
        retailer: "MakeMyTrip",
        price: 3599,
        currency: "INR",
        url: "https://makemytrip.com",
        availability: "limited",
      },
    ],
    ratings: { average: 4.0, count: 4234 },
    tags: ["domestic", "budget", "evening"],
  },
  {
    id: "prod-17",
    name: "Delhi to Goa - Vistara (10:00 AM)",
    category: "flights",
    brand: "Vistara",
    description: "2h 35min non-stop flight with premium service",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400&h=400&fit=crop",
    specifications: {
      departure: "10:00 AM",
      duration: "2h 35min",
      stops: "Non-stop",
      aircraft: "A320",
      date: "Dec 16, 2024",
    },
    prices: [
      {
        retailer: "Vistara Official",
        price: 5999,
        currency: "INR",
        url: "https://vistara.com",
        availability: "in_stock",
      },
      {
        retailer: "MakeMyTrip",
        price: 6299,
        currency: "INR",
        url: "https://makemytrip.com",
        availability: "in_stock",
      },
      {
        retailer: "Cleartrip",
        price: 6099,
        currency: "INR",
        url: "https://cleartrip.com",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.8, count: 3456 },
    tags: ["domestic", "premium", "morning"],
  },

  // ============ HOTELS ============
  {
    id: "prod-18",
    name: "Taj Hotels Delhi",
    category: "hotels",
    brand: "Taj Hotels",
    description: "5-star luxury hotel in central Delhi with world-class amenities",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=400&fit=crop",
    specifications: {
      star_rating: "5",
      location: "New Delhi",
      room_type: "Deluxe Double",
      amenities: "WiFi, AC, Pool, Gym, Spa",
      check_in: "2:00 PM",
      check_out: "11:00 AM",
    },
    prices: [
      {
        retailer: "Taj Hotels",
        price: 18999,
        currency: "INR",
        url: "https://tajhotels.com",
        availability: "in_stock",
      },
      {
        retailer: "OYO",
        price: 15999,
        currency: "INR",
        url: "https://oyorooms.com",
        availability: "in_stock",
      },
      {
        retailer: "MakeMyTrip",
        price: 17499,
        currency: "INR",
        url: "https://makemytrip.com",
        availability: "in_stock",
      },
      {
        retailer: "Booking.com",
        price: 16999,
        currency: "INR",
        url: "https://booking.com",
        availability: "limited",
      },
    ],
    ratings: { average: 4.6, count: 5421 },
    tags: ["luxury", "5-star", "delhi"],
  },
  {
    id: "prod-19",
    name: "OYO Hotel Mumbai",
    category: "hotels",
    brand: "OYO",
    description: "Budget-friendly hotel with clean rooms and essential amenities",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=400&fit=crop",
    specifications: {
      star_rating: "3",
      location: "Mumbai",
      room_type: "Single Room",
      amenities: "WiFi, AC, Bathroom",
      check_in: "2:00 PM",
      check_out: "11:00 AM",
    },
    prices: [
      {
        retailer: "OYO Official",
        price: 2999,
        currency: "INR",
        url: "https://oyorooms.com",
        availability: "in_stock",
      },
      {
        retailer: "MakeMyTrip",
        price: 3299,
        currency: "INR",
        url: "https://makemytrip.com",
        availability: "in_stock",
      },
      {
        retailer: "Booking.com",
        price: 3099,
        currency: "INR",
        url: "https://booking.com",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.0, count: 8765 },
    tags: ["budget", "3-star", "mumbai"],
  },
  {
    id: "prod-20",
    name: "ITC Maurya Bangalore",
    category: "hotels",
    brand: "ITC",
    description: "Premium 5-star business hotel with Ayurveda spa",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=400&fit=crop",
    specifications: {
      star_rating: "5",
      location: "Bangalore",
      room_type: "Suite",
      amenities: "WiFi, AC, Pool, Gym, Spa, Restaurant",
      check_in: "2:00 PM",
      check_out: "12:00 PM",
    },
    prices: [
      {
        retailer: "ITC Hotels",
        price: 22999,
        currency: "INR",
        url: "https://itchotels.com",
        availability: "in_stock",
      },
      {
        retailer: "MakeMyTrip",
        price: 21499,
        currency: "INR",
        url: "https://makemytrip.com",
        availability: "in_stock",
      },
      {
        retailer: "Booking.com",
        price: 20999,
        currency: "INR",
        url: "https://booking.com",
        availability: "limited",
      },
    ],
    ratings: { average: 4.7, count: 3214 },
    tags: ["luxury", "5-star", "bangalore"],
  },
  {
    id: "prod-21",
    name: "Marriott Kolkata",
    category: "hotels",
    brand: "Marriott",
    description: "International 5-star chain with modern amenities",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=400&fit=crop",
    specifications: {
      star_rating: "5",
      location: "Kolkata",
      room_type: "Deluxe Room",
      amenities: "WiFi, AC, Pool, Gym, Bar, Restaurant",
      check_in: "3:00 PM",
      check_out: "11:00 AM",
    },
    prices: [
      {
        retailer: "Marriott",
        price: 19999,
        currency: "INR",
        url: "https://marriott.com",
        availability: "in_stock",
      },
      {
        retailer: "MakeMyTrip",
        price: 18999,
        currency: "INR",
        url: "https://makemytrip.com",
        availability: "in_stock",
      },
      {
        retailer: "Booking.com",
        price: 18499,
        currency: "INR",
        url: "https://booking.com",
        availability: "in_stock",
      },
    ],
    ratings: { average: 4.5, count: 4567 },
    tags: ["luxury", "5-star", "kolkata"],
  },
]

export function getProductsByCategory(category: string): Product[] {
  return mockProducts.filter((p) => p.category === category)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return mockProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.brand.toLowerCase().includes(lowerQuery) ||
      p.description.toLowerCase().includes(lowerQuery),
  )
}

export function filterProducts(
  products: Product[],
  priceMin: number,
  priceMax: number,
  brands: string[] = [],
  minRating = 0,
): Product[] {
  return products.filter((p) => {
    const minPrice = Math.min(...p.prices.map((pr) => pr.price))
    const passesPrice = minPrice >= priceMin && minPrice <= priceMax
    const passesBrand = brands.length === 0 || brands.includes(p.brand)
    const passesRating = p.ratings.average >= minRating
    return passesPrice && passesBrand && passesRating
  })
}
